### ISSUE TITLE
'onlooker' machines generated using this code.

### ISSUE THREAD

**Issue by zcaicaros** [sebastian-knopp/cjs-instances#1]
Hi Dr. Sebastian Knopp,

Congratulations to your amazing work! I am a PhD student from Singapore and now learning from your paper.

When I use your instance generation code, I found in some instances there are certain machines that do not appear in any recipes.

For example in the following instance:

10 20 20
TWT
17 219 7 10 6 6 18 15 8 2 6 7 13 3
7 263 1 10 3 7 4 10 6 5 10 19 8 10
7 301 3 10 6 16 7 8 2 19 1 19 15 0
14 294 6 10 18 16 14 8 19 12 16 5 6 3
10 246 5 10 14 1 12 12 0 4 10 0 0 1
0 226 8 10 13 7 7 4 7 2 11 8 1 0
2 300 4 10 10 11 4 19 15 14 19 17 3 12
13 279 3 10 10 5 19 3 1 18 0 18 19 15
9 223 1 10 2 6 10 9 8 2 12 8 15 3
8 230 7 10 17 5 15 18 17 8 14 14 4 1
6
6
6
6
6
6
6
6
6
6
1
1
1
1
1
1
1
1
1
1
4 6 10 5 12 3 4 4 2
4 3 16 7 13 1 14 6 4
5 1 12 7 13 2 6 4 19 6 13
2 0 3 4 13
2 7 4 8 5
4 7 4 4 11 6 2 2 3
4 2 18 1 1 8 16 9 7
1 0 11
3 1 20 7 10 4 11
5 2 16 1 5 6 3 7 8 5 2
3 10 18 12 3 18 10
4 18 10 10 3 17 9 19 12
1 15 9
3 15 7 13 13 17 18
1 13 8
5 13 6 17 7 12 7 11 9 16 8
3 18 6 10 11 16 8
1 12 12
3 19 4 13 16 16 12
2 13 2 12 8
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 3 8 6 6 2 1 5 2 9
0 0 0 0 0 0 0 0 0 0 1 0 10 10 2 9 10 2 9 2
0 0 0 0 0 0 0 0 0 0 9 8 0 6 7 1 1 9 2 5
0 0 0 0 0 0 0 0 0 0 5 2 3 0 5 7 10 10 5 10
0 0 0 0 0 0 0 0 0 0 3 6 4 7 0 3 2 2 1 2
0 0 0 0 0 0 0 0 0 0 6 6 5 4 6 0 2 10 9 6
0 0 0 0 0 0 0 0 0 0 4 8 7 4 6 6 0 10 7 10
0 0 0 0 0 0 0 0 0 0 7 7 10 5 4 10 9 0 5 2
0 0 0 0 0 0 0 0 0 0 7 5 4 7 9 6 5 7 0 8
0 0 0 0 0 0 0 0 0 0 7 9 3 4 3 3 5 5 1 0

machine number 14 is not contained in any recipes.

However in your industrial instances, no such situations happen.

Is this a bug?

Looking forward to your reply.

Regards,
Cong

**Comment by sebastian-knopp** [comment]
Hello @zcajiayin, thank you for the comment. You are right, the instance generator does not directly take balancing of recipes to machines into account and, as you observed, it could happen that for some machines there are no recipes. One could just interpret this as an instance with one machines less. Some configurations of the generator make this more likely than others. In that regard, the generated instances are not as realistic as they could be, compared to industrial instances.

**Comment by zcaicaros** [comment]
"One could just interpret this as an instance with one machines less." That's one of the right way of interpreting this. Thanks for your reply!
