### ISSUE TITLE
Problem(error) in instance industry09

### ISSUE THREAD

**Issue by stephenzhangxl** [sebastian-knopp/cjs-instances#4]
Dear Knopp,

Your work on complex job shop problem is greate, and  It inspired me to follow your research line and do test with your instances.
Recently, I encountered a problem when testing industry09.
In instance industry09, there is a problem in line 433. 
This line reads: 4 5 159 5 166 15 166 17 162. 
This line is a description of an operation family. The problem is  machine 5 exists in two different recipes, i.e. 5 159 and 5 166.
I think this maybe is a typo here. Could you have a look at it?

Look forward to your reply!
thanks!

**Comment by sebastian-knopp** [comment]
This probably is an artifact from the conversion of actual industrial data to anonymized instances. The longer processing duration of 166 is possible (but makes no sense given the considered objective functions). So, "5 166" can just be ignored and one could use only "5 159".
